services:
  backend:
    command: ["bash", "./scripts/startup.sh"]
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/service
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - fishdb:/var/lib/postgresql/data/

  nginx:
    image: nginx:stable-alpine3.17-slim
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot



volumes:
  certbot-etc:
  certbot-var:
  fishdb:
    driver: local
