# Generated by Django 5.2 on 2025-06-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='for_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
